Create Day7.cpp
iodump01/IODumpChaitraChallenge pull request #4
Opened 2023-03-30 12:26 UTC by sohampathak1234

Day 8 of our IODump Chaitra challenge!

Program to print multiplication table of a number using for loop

2023-03-30 12:40 UTC, ganimtron-10 requested changes
Hey @sohampathak1234,
This PR is close to be merged, just look at below comments!

2023-03-30 12:40 UTC, ganimtron-10 commented on CPP/Day7.cpp
> +Day 7 : Program to print multiplication table of a number using for loop
`Day 8` instead of `7`

2023-03-30 12:40 UTC, ganimtron-10 commented on CPP/Day7.cpp
> +/*
File name should be `Day8.cpp`

2023-03-31 05:46 UTC, sohampathak1234 commented
Done

2023-03-31 14:17 UTC, merged

2023-03-31 14:17 UTC, ganimtron-10 commented
Thanks for the changes! Merging!

2023-04-06 16:53 UTC, sohampathak1234 commented
Your Welcome!